# Generated by Django 5.2.6 on 2025-11-07 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="section_users",
                to="auth_custom.section",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unit_users",
                to="auth_custom.unit",
            ),
        ),
    ]
