# Generated by Django 5.2.6 on 2025-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0002_user_section_user_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Suspended", "Suspended"),
                    ("Locked", "Locked"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
