# Generated by Django 5.2.6 on 2025-11-10 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0006_cleanup_old_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signer_username", models.CharField(max_length=150)),
                ("signer_full_name", models.CharField(max_length=255)),
                ("signer_role", models.CharField(max_length=100)),
                ("signer_email", models.EmailField(max_length=254)),
                ("password_verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authentication_method",
                    models.CharField(
                        choices=[
                            ("PASSWORD", "Password"),
                            ("CERTIFICATE", "Certificate"),
                        ],
                        default="PASSWORD",
                        max_length=50,
                    ),
                ),
                (
                    "signature_type",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                            ("ACKNOWLEDGE", "Acknowledged"),
                            ("CREATE", "Created"),
                            ("ALLOCATE", "Allocated"),
                            ("ISSUE", "Issued"),
                            ("RETURN", "Returned"),
                            ("DESTROY", "Destroyed"),
                            ("MODIFY", "Modified"),
                            ("REVIEW", "Reviewed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("signature_purpose", models.TextField()),
                ("signature_timestamp", models.DateTimeField(auto_now_add=True)),
                ("signed_model", models.CharField(max_length=100)),
                ("signed_record_id", models.IntegerField()),
                ("signed_record_description", models.TextField()),
                ("data_hash", models.CharField(max_length=64, unique=True)),
                ("signature_data", models.JSONField()),
                ("signature_hash", models.CharField(max_length=64, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("invalidation_reason", models.TextField(blank=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("audit_trail_id", models.IntegerField(blank=True, null=True)),
                (
                    "invalidated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invalidated_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "digital_signatures",
                "ordering": ["-signature_timestamp"],
                "permissions": [
                    ("view_all_signatures", "Can view all digital signatures"),
                    ("invalidate_signature", "Can invalidate signatures (QA only)"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SignatureHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_timestamp", models.DateTimeField(auto_now_add=True)),
                ("verification_result", models.BooleanField()),
                ("verification_message", models.TextField()),
                (
                    "signature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_history",
                        to="auth_custom.digitalsignature",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "signature_verification_history",
                "ordering": ["-verification_timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="digitalsignature",
            index=models.Index(
                fields=["signer", "signature_timestamp"],
                name="digital_sig_signer__20fedb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalsignature",
            index=models.Index(
                fields=["signed_model", "signed_record_id"],
                name="digital_sig_signed__4ac829_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="digitalsignature",
            index=models.Index(
                fields=["signature_type"], name="digital_sig_signatu_1cabd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="digitalsignature",
            index=models.Index(
                fields=["data_hash"], name="digital_sig_data_ha_16c709_idx"
            ),
        ),
    ]
