# Generated by Django 5.2.6 on 2025-11-10 16:53

from django.db import migrations


def update_to_four_roles(apps, schema_editor):
    """
    Update from 5 roles to 4 roles:
    OLD ROLES:
    1. System Administrator
    2. Section Head
    3. Head QC
    4. Document Store
    5. Quality Assurance

    NEW ROLES:
    1. System Admin (setup storage, departments, sections, user management)
    2. Section Head (approve/reject requests)
    3. Store Head (allocate storage, reallocate crates)
    4. User (create requests)

    MAPPING:
    - System Administrator -> System Admin
    - Head QC -> Section Head (they approve requests)
    - Document Store -> Store Head (they allocate storage)
    - Section Head -> User (they create requests)
    - Quality Assurance -> Remove (or map to User if needed)
    """
    Role = apps.get_model('auth_custom', 'Role')
    User = apps.get_model('auth_custom', 'User')

    # Create new roles
    system_admin, _ = Role.objects.get_or_create(
        role_name='System Admin',
        defaults={'description': 'Setup storage units, departments, sections, and user management'}
    )

    section_head, _ = Role.objects.get_or_create(
        role_name='Section Head',
        defaults={'description': 'Approve or reject requests'}
    )

    store_head, _ = Role.objects.get_or_create(
        role_name='Store Head',
        defaults={'description': 'Allocate crate storage locations and reallocate crates'}
    )

    user_role, _ = Role.objects.get_or_create(
        role_name='User',
        defaults={'description': 'Create new requests'}
    )

    # Map old roles to new roles
    try:
        old_system_admin = Role.objects.get(role_name='System Administrator')
        User.objects.filter(role=old_system_admin).update(role=system_admin)
        print(f"Migrated System Administrator users to System Admin")
    except Role.DoesNotExist:
        pass

    try:
        old_head_qc = Role.objects.get(role_name='Head QC')
        User.objects.filter(role=old_head_qc).update(role=section_head)
        print(f"Migrated Head QC users to Section Head")
    except Role.DoesNotExist:
        pass

    try:
        old_document_store = Role.objects.get(role_name='Document Store')
        User.objects.filter(role=old_document_store).update(role=store_head)
        print(f"Migrated Document Store users to Store Head")
    except Role.DoesNotExist:
        pass

    try:
        old_section_head = Role.objects.get(role_name='Section Head')
        # Old Section Head created requests, so they become User
        User.objects.filter(role=old_section_head).update(role=user_role)
        print(f"Migrated old Section Head users to User role")
    except Role.DoesNotExist:
        pass

    try:
        old_qa = Role.objects.get(role_name='Quality Assurance')
        # QA had read-only access, map to User role for now
        User.objects.filter(role=old_qa).update(role=user_role)
        print(f"Migrated Quality Assurance users to User role")
    except Role.DoesNotExist:
        pass

    # Delete old roles (after users have been reassigned)
    Role.objects.filter(role_name__in=[
        'System Administrator',
        'Head QC',
        'Document Store',
        'Quality Assurance'
    ]).delete()

    print("Role migration complete: Updated to 4-role system")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - recreate old 5 roles
    """
    Role = apps.get_model('auth_custom', 'Role')

    # Recreate old roles
    Role.objects.get_or_create(
        role_name='System Administrator',
        defaults={'description': 'Manages users, roles, and system configurations'}
    )

    Role.objects.get_or_create(
        role_name='Section Head',
        defaults={'description': 'Creates storage, withdrawal, and destruction requests'}
    )

    Role.objects.get_or_create(
        role_name='Head QC',
        defaults={'description': 'Approves or rejects requests'}
    )

    Role.objects.get_or_create(
        role_name='Document Store',
        defaults={'description': 'Allocates storage and manages physical documents'}
    )

    Role.objects.get_or_create(
        role_name='Quality Assurance',
        defaults={'description': 'Read-only oversight and auditing'}
    )


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0007_add_digital_signature_models"),
    ]

    operations = [
        migrations.RunPython(update_to_four_roles, reverse_migration),
    ]
