# Generated by Django 5.2.6 on 2025-11-11 06:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0008_update_to_four_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userunit",
            options={
                "verbose_name": "User Unit Assignment",
                "verbose_name_plural": "User Unit Assignments",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="units",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_users",
                through="auth_custom.UserUnit",
                to="auth_custom.unit",
            ),
        ),
        migrations.AddField(
            model_name="userunit",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userunit",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="user_assignments", to="auth_custom.department"
            ),
        ),
        migrations.AlterField(
            model_name="userunit",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_user_assignments",
                to="auth_custom.unit",
            ),
        ),
        migrations.AlterField(
            model_name="userunit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_unit_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
