# Generated by Django 5.2.6 on 2025-11-11 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0009_alter_userunit_options_user_units_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionPolicy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "session_timeout_minutes",
                    models.IntegerField(
                        choices=[
                            (15, "15 minutes"),
                            (30, "30 minutes"),
                            (60, "1 hour"),
                            (120, "2 hours"),
                            (240, "4 hours"),
                            (480, "8 hours"),
                        ],
                        default=30,
                        help_text="Session timeout in minutes (automatically logs out inactive users)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_policy_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Policy",
                "verbose_name_plural": "Session Policies",
                "db_table": "session_policy",
            },
        ),
    ]
