# Generated by Django 5.2.6 on 2025-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0010_sessionpolicy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionpolicy",
            name="session_timeout_minutes",
            field=models.IntegerField(
                choices=[
                    (5, "5 minutes"),
                    (10, "10 minutes"),
                    (15, "15 minutes"),
                    (20, "20 minutes"),
                    (25, "25 minutes"),
                    (30, "30 minutes"),
                ],
                default=30,
                help_text="Session timeout in minutes (automatically logs out inactive users)",
            ),
        ),
    ]
