# Generated by Django 4.2.7 on 2025-11-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0013_user_sections"),
    ]

    operations = [
        migrations.CreateModel(
            name="Privilege",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "codename",
                    models.CharField(
                        help_text="Unique identifier like 'create_request'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name like 'Create Request'",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("requests", "Requests"),
                            ("storage", "Storage Operations"),
                            ("users", "User Management"),
                            ("master_data", "Master Data"),
                            ("reports", "Reports"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Privilege",
                "verbose_name_plural": "Privileges",
                "db_table": "privileges",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="RolePrivilege",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "privilege",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privilege_roles",
                        to="auth_custom.privilege",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_privileges",
                        to="auth_custom.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Privilege",
                "verbose_name_plural": "Role Privileges",
                "db_table": "role_privileges",
                "unique_together": {("role", "privilege")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="privileges",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="auth_custom.RolePrivilege",
                to="auth_custom.privilege",
            ),
        ),
    ]
