# Generated by Django migration
from django.db import migrations


def seed_privileges(apps, schema_editor):
    """Create default privileges and assign to core roles"""
    Privilege = apps.get_model('auth_custom', 'Privilege')
    Role = apps.get_model('auth_custom', 'Role')
    RolePrivilege = apps.get_model('auth_custom', 'RolePrivilege')

    # Define all privileges
    privileges_data = [
        # Request privileges
        {'codename': 'create_request', 'name': 'Create Request', 'description': 'Create storage, withdrawal, and destruction requests', 'category': 'requests'},
        {'codename': 'approve_request', 'name': 'Approve Request', 'description': 'Approve or reject requests', 'category': 'requests'},
        {'codename': 'view_requests', 'name': 'View Requests', 'description': 'View all requests', 'category': 'requests'},
        {'codename': 'view_own_requests', 'name': 'View Own Requests', 'description': 'View only own requests', 'category': 'requests'},

        # Storage privileges
        {'codename': 'allocate_storage', 'name': 'Allocate Storage', 'description': 'Allocate storage locations to approved requests', 'category': 'storage'},
        {'codename': 'reallocate_storage', 'name': 'Reallocate Storage', 'description': 'Reallocate crates to different locations', 'category': 'storage'},
        {'codename': 'issue_withdrawal', 'name': 'Issue Withdrawal', 'description': 'Issue documents for withdrawal', 'category': 'storage'},
        {'codename': 'return_withdrawal', 'name': 'Return Withdrawal', 'description': 'Return documents after withdrawal', 'category': 'storage'},
        {'codename': 'confirm_destruction', 'name': 'Confirm Destruction', 'description': 'Confirm document destruction', 'category': 'storage'},
        {'codename': 'view_storage', 'name': 'View Storage', 'description': 'View storage locations and crates', 'category': 'storage'},
        {'codename': 'manage_storage', 'name': 'Manage Storage', 'description': 'Create and edit storage locations', 'category': 'storage'},

        # User management privileges
        {'codename': 'manage_users', 'name': 'Manage Users', 'description': 'Create, edit, and delete users', 'category': 'users'},
        {'codename': 'view_users', 'name': 'View Users', 'description': 'View user list and details', 'category': 'users'},
        {'codename': 'manage_roles', 'name': 'Manage Roles', 'description': 'Create, edit, and delete roles', 'category': 'users'},
        {'codename': 'reset_passwords', 'name': 'Reset Passwords', 'description': 'Reset user passwords', 'category': 'users'},
        {'codename': 'unlock_accounts', 'name': 'Unlock Accounts', 'description': 'Unlock locked user accounts', 'category': 'users'},

        # Master data privileges
        {'codename': 'manage_master_data', 'name': 'Manage Master Data', 'description': 'Manage units, departments, sections', 'category': 'master_data'},
        {'codename': 'manage_units', 'name': 'Manage Units', 'description': 'Create and edit units', 'category': 'master_data'},
        {'codename': 'manage_departments', 'name': 'Manage Departments', 'description': 'Create and edit departments', 'category': 'master_data'},
        {'codename': 'manage_sections', 'name': 'Manage Sections', 'description': 'Create and edit sections', 'category': 'master_data'},

        # Reports privileges
        {'codename': 'view_reports', 'name': 'View Reports', 'description': 'View all reports', 'category': 'reports'},
        {'codename': 'export_reports', 'name': 'Export Reports', 'description': 'Export reports to Excel/PDF', 'category': 'reports'},
        {'codename': 'view_audit_trails', 'name': 'View Audit Trails', 'description': 'View audit trail logs', 'category': 'reports'},
        {'codename': 'view_dashboard', 'name': 'View Dashboard', 'description': 'Access main dashboard', 'category': 'reports'},

        # System privileges
        {'codename': 'use_barcode_scanner', 'name': 'Use Barcode Scanner', 'description': 'Use barcode scanner functionality', 'category': 'system'},
        {'codename': 'digital_signature', 'name': 'Apply Digital Signature', 'description': 'Apply digital signatures to documents', 'category': 'system'},
        {'codename': 'view_all_units', 'name': 'View All Units', 'description': 'View data across all units', 'category': 'system'},
        {'codename': 'manage_session_policy', 'name': 'Manage Session Policy', 'description': 'Configure session timeout settings', 'category': 'system'},
    ]

    # Create privileges
    privileges = {}
    for priv_data in privileges_data:
        privilege, created = Privilege.objects.get_or_create(
            codename=priv_data['codename'],
            defaults={
                'name': priv_data['name'],
                'description': priv_data['description'],
                'category': priv_data['category'],
                'is_active': True,
            }
        )
        privileges[priv_data['codename']] = privilege

    # Define role-privilege mappings
    role_privileges = {
        'System Admin': [
            'manage_users', 'view_users', 'manage_roles', 'reset_passwords', 'unlock_accounts',
            'manage_master_data', 'manage_units', 'manage_departments', 'manage_sections',
            'manage_storage', 'view_storage',
            'view_reports', 'export_reports', 'view_audit_trails', 'view_dashboard',
            'view_requests', 'view_all_units', 'manage_session_policy',
        ],
        'Section Head': [
            'approve_request', 'view_requests', 'view_own_requests',
            'view_reports', 'view_audit_trails', 'view_dashboard',
            'digital_signature',
        ],
        'Store Head': [
            'allocate_storage', 'reallocate_storage',
            'issue_withdrawal', 'return_withdrawal', 'confirm_destruction',
            'view_storage', 'view_requests',
            'view_reports', 'view_audit_trails', 'view_dashboard',
            'use_barcode_scanner',
        ],
        'User': [
            'create_request', 'view_own_requests',
            'view_reports', 'view_dashboard',
            'use_barcode_scanner',
        ],
    }

    # Assign privileges to roles
    for role_name, privilege_codes in role_privileges.items():
        try:
            role = Role.objects.get(role_name=role_name)
            for priv_code in privilege_codes:
                if priv_code in privileges:
                    RolePrivilege.objects.get_or_create(
                        role=role,
                        privilege=privileges[priv_code]
                    )
        except Role.DoesNotExist:
            # Role doesn't exist yet, will be created when user is assigned
            pass


def reverse_seed_privileges(apps, schema_editor):
    """Remove seeded privileges"""
    Privilege = apps.get_model('auth_custom', 'Privilege')
    Privilege.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0014_add_privilege_model'),
    ]

    operations = [
        migrations.RunPython(seed_privileges, reverse_seed_privileges),
    ]
