# Generated by Django 4.2.7 on 2025-11-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0015_seed_privileges"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="role",
            name="is_core_role",
            field=models.BooleanField(
                default=False, help_text="Core roles cannot be deleted"
            ),
        ),
    ]
