# Generated by Django 4.2.7 on 2025-11-21 07:28

from django.db import migrations


def mark_core_roles(apps, schema_editor):
    """Mark the 4 core system roles as is_core_role=True"""
    Role = apps.get_model('auth_custom', 'Role')

    core_role_names = [
        'System Admin',
        'Section Head',
        'Store Head',
        'User'
    ]

    for role_name in core_role_names:
        role = Role.objects.filter(role_name=role_name).first()
        if role:
            role.is_core_role = True
            role.save(update_fields=['is_core_role'])
            print(f'Marked {role_name} as core role')
        else:
            print(f'Warning: Core role {role_name} not found')


def reverse_mark_core_roles(apps, schema_editor):
    """Reverse the marking of core roles"""
    Role = apps.get_model('auth_custom', 'Role')
    Role.objects.filter(is_core_role=True).update(is_core_role=False)


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0016_add_role_flags"),
    ]

    operations = [
        migrations.RunPython(mark_core_roles, reverse_mark_core_roles),
    ]
