# Generated by Django 4.2.7 on 2025-11-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0017_mark_core_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, help_text="Last password change timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_expired",
            field=models.BooleanField(
                default=False, help_text="True if password has expired"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_expiry_days",
            field=models.IntegerField(
                default=90, help_text="Password expires after this many days (max 90)"
            ),
        ),
    ]
