# Generated by Django 4.2.7 on 2025-11-27 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_custom", "0018_user_password_changed_at_user_password_expired_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_expiry_days",
        ),
        migrations.CreateModel(
            name="PasswordPolicy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "password_expiry_days",
                    models.IntegerField(
                        default=90,
                        help_text="Password expires after this many days (1-90)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="password_policy_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Policy",
                "verbose_name_plural": "Password Policies",
                "db_table": "password_policy",
            },
        ),
    ]
