# Generated by Django 5.2.6 on 2025-10-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("action_time", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Deleted", "Deleted"),
                            ("Viewed", "Viewed"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Issued", "Issued"),
                            ("Returned", "Returned"),
                            ("Allocated", "Allocated"),
                        ],
                        editable=False,
                        max_length=255,
                    ),
                ),
                (
                    "request_id",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "storage_id",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "crate_id",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "document_id",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("message", models.TextField(editable=False)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, editable=False, max_length=500),
                ),
            ],
            options={
                "verbose_name": "Audit Trail",
                "verbose_name_plural": "Audit Trails",
                "db_table": "audit_trail",
                "ordering": ["-action_time"],
                "permissions": [],
            },
        ),
    ]
