# Generated by Django 5.2.6 on 2025-10-27 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["action_time"], name="audit_trail_action__df96bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(fields=["user"], name="audit_trail_user_id_acf306_idx"),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(fields=["action"], name="audit_trail_action_5388db_idx"),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["request_id"], name="audit_trail_request_79769b_idx"
            ),
        ),
    ]
