# Generated by Django 4.2.7 on 2025-11-18 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="attempted_username",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name="audittrail",
            name="action",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Updated", "Updated"),
                    ("Deleted", "Deleted"),
                    ("Viewed", "Viewed"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Issued", "Issued"),
                    ("Returned", "Returned"),
                    ("Allocated", "Allocated"),
                    ("Login", "Login"),
                    ("LoginFailed", "LoginFailed"),
                    ("Logout", "Logout"),
                ],
                editable=False,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="audittrail",
            name="user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
