# Generated by Django 4.2.7 on 2025-11-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_add_login_audit_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audittrail",
            name="action",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Updated", "Updated"),
                    ("Deleted", "Deleted"),
                    ("Viewed", "Viewed"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Issued", "Issued"),
                    ("Returned", "Returned"),
                    ("Allocated", "Allocated"),
                    ("Login", "Login"),
                    ("LoginFailed", "LoginFailed"),
                    ("Logout", "Logout"),
                    ("SessionTimeout", "SessionTimeout"),
                    ("SessionTerminated", "SessionTerminated"),
                ],
                editable=False,
                max_length=255,
            ),
        ),
    ]
