# Generated by Django 5.2.6 on 2025-10-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_custom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("room_name", models.CharField(max_length=100)),
                ("rack_name", models.CharField(max_length=100)),
                ("compartment_name", models.CharField(max_length=100)),
                ("shelf_name", models.CharField(max_length=100)),
                ("is_occupied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storages",
                        to="auth_custom.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage",
                "verbose_name_plural": "Storages",
                "db_table": "storages",
                "indexes": [
                    models.Index(
                        fields=["unit", "room_name"], name="storages_unit_id_d27e69_idx"
                    ),
                    models.Index(
                        fields=["is_occupied"], name="storages_is_occu_f1037d_idx"
                    ),
                ],
                "unique_together": {
                    ("unit", "room_name", "rack_name", "compartment_name", "shelf_name")
                },
            },
        ),
    ]
