# Generated by Django 5.2.6 on 2025-11-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="storage",
            name="storages_is_occu_f1037d_idx",
        ),
        migrations.RemoveField(
            model_name="storage",
            name="is_occupied",
        ),
        migrations.AlterField(
            model_name="storage",
            name="shelf_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
