# Generated by Django 5.2.6 on 2025-10-27 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_custom", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("Storage", "Storage"),
                            ("Withdrawal", "Withdrawal"),
                            ("Destruction", "Destruction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("issue_date", models.DateTimeField(blank=True, null=True)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("expected_return_date", models.DateTimeField(blank=True, null=True)),
                ("allocation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Issued", "Issued"),
                            ("Returned", "Returned"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("purpose", models.TextField(blank=True)),
                ("full_withdrawal", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocated_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="documents.crate",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="auth_custom.unit",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawn_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
                "db_table": "requests",
            },
        ),
        migrations.CreateModel(
            name="RequestDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="requests.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Document",
                "verbose_name_plural": "Request Documents",
                "db_table": "request_documents",
                "unique_together": {("request", "document")},
            },
        ),
        migrations.AddField(
            model_name="request",
            name="documents",
            field=models.ManyToManyField(
                blank=True, through="requests.RequestDocument", to="documents.document"
            ),
        ),
        migrations.CreateModel(
            name="SendBack",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_sendbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sendbacks",
                        to="requests.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "SendBack",
                "verbose_name_plural": "SendBacks",
                "db_table": "sendbacks",
            },
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["request_type", "status"], name="requests_request_9ff4f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["status"], name="requests_status_58d546_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["request_date"], name="requests_request_cd2181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["unit"], name="requests_unit_id_d30f2a_idx"),
        ),
    ]
