# Generated by Django 5.2.6 on 2025-11-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sendback",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "SendBack",
                "verbose_name_plural": "SendBacks",
            },
        ),
        migrations.AddField(
            model_name="sendback",
            name="sendback_type",
            field=models.CharField(
                choices=[
                    ("Change Request", "Change Request"),
                    ("Return Note", "Return Note"),
                ],
                default="Change Request",
                help_text="Type of sendback: Change Request or Return Note",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Sent Back", "Sent Back"),
                    ("Approved", "Approved"),
                    ("Issued", "Issued"),
                    ("Returned", "Returned"),
                    ("Rejected", "Rejected"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sendback",
            name="reason",
            field=models.TextField(help_text="Reason for sending back or return notes"),
        ),
    ]
