# Generated by Django 5.2.6 on 2025-10-27 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_custom", "0001_initial"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("destruction_date", models.DateField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Archived", "Archived"),
                            ("Destroyed", "Destroyed"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_crates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crates",
                        to="storage.storage",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crates",
                        to="auth_custom.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crate",
                "verbose_name_plural": "Crates",
                "db_table": "crates",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("document_name", models.CharField(max_length=255)),
                ("document_number", models.CharField(max_length=100, unique=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("Physical", "Physical"), ("Digital", "Digital")],
                        default="Physical",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "indexes": [
                    models.Index(
                        fields=["document_number"], name="documents_documen_19bab8_idx"
                    ),
                    models.Index(
                        fields=["document_type"], name="documents_documen_fc21d0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CrateDocument",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.crate",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crate Document",
                "verbose_name_plural": "Crate Documents",
                "db_table": "crate_documents",
                "unique_together": {("document", "crate")},
            },
        ),
        migrations.AddField(
            model_name="crate",
            name="documents",
            field=models.ManyToManyField(
                through="documents.CrateDocument", to="documents.document"
            ),
        ),
        migrations.AddIndex(
            model_name="crate",
            index=models.Index(fields=["status"], name="crates_status_697dca_idx"),
        ),
        migrations.AddIndex(
            model_name="crate",
            index=models.Index(
                fields=["destruction_date"], name="crates_destruc_7a9f14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crate",
            index=models.Index(fields=["unit"], name="crates_unit_id_e188f1_idx"),
        ),
    ]
