# Generated by Django 5.2.6 on 2025-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crate",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Withdrawn", "Withdrawn"),
                    ("Archived", "Archived"),
                    ("Destroyed", "Destroyed"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
